name: FlingPads
main: uk.co.reosh.FlingPads.FlingPads
authors: [Cross, WickedSkipper]
website: https://github.com/REOSH/mc-flingpads
version: ${project.version}
description: A small plugin that boosts player horizontally upon walking on pressure plate.
